# Generated by Django 3.0.5 on 2020-05-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heroinfo',
            old_name='hanme',
            new_name='hname',
        ),
    ]
